#!/usr/bin/env python3
"""Independent verifier for agent action receipts (draft-sahu-agent-action-receipts).

This is a from-scratch second implementation, deliberately NOT a port of the
producing implementation: the vectors in this repository were generated by one
implementation and must verify under this one. Requires: pip install cryptography

Usage:
  verify.py <log.jsonl>        verify one receipt log (exit 0 = all good)
  verify.py --manifest [dir]   run every vector against manifest.json expectations
"""
import hashlib
import json
import re
import sys
from pathlib import Path

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

HEX64 = re.compile(r"^[0-9a-f]{64}$")
HEX128 = re.compile(r"^[0-9a-f]{128}$")


def canon_json(v):
    """Compact JSON with object members sorted by Unicode code point, recursively.
    Applied to `params` only. Arrays keep order. Integers only (the draft's
    interoperability constraint); floats are refused rather than guessed."""
    if v is None:
        return "null"
    if v is True:
        return "true"
    if v is False:
        return "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        raise ValueError("non-integer number in signed members (interoperability constraint)")
    if isinstance(v, str):
        return json.dumps(v, ensure_ascii=False)
    if isinstance(v, list):
        return "[" + ",".join(canon_json(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ",".join(
            json.dumps(k, ensure_ascii=False) + ":" + canon_json(v[k]) for k in sorted(v)
        ) + "}"
    raise ValueError(f"unsupported JSON type: {type(v)}")


def canonical_bytes(r):
    """The signed byte sequence: fixed member order (NOT lexicographic), params
    sorted recursively, actor as {agent,user} in that order, total omission of
    absent actor/prev_hash."""
    parts = [
        '"step_id":' + json.dumps(r["step_id"], ensure_ascii=False),
        '"action_id":' + json.dumps(r["action_id"], ensure_ascii=False),
        '"params":' + canon_json(r["params"]),
        '"success":' + ("true" if r["success"] else "false"),
        '"ts_ms":' + str(r["ts_ms"]),
    ]
    if "actor" in r and r["actor"] is not None:
        a = r["actor"]
        parts.append(
            '"actor":{"agent":' + json.dumps(a["agent"], ensure_ascii=False)
            + ',"user":' + json.dumps(a["user"], ensure_ascii=False) + "}"
        )
    if "prev_hash" in r and r["prev_hash"] is not None:
        parts.append('"prev_hash":' + json.dumps(r["prev_hash"], ensure_ascii=False))
    return ("{" + ",".join(parts) + "}").encode("utf-8")


def verify_receipt(r):
    """Returns None if the signature verifies, else a reason string."""
    try:
        if not isinstance(r.get("step_id"), str):
            return "step_id must be a string"
        if not isinstance(r.get("action_id"), str):
            return "action_id must be a string"
        if "params" not in r:
            return "params is required"
        if not isinstance(r.get("success"), bool):
            return "success must be a boolean"
        if not isinstance(r.get("ts_ms"), int) or isinstance(r.get("ts_ms"), bool) or r["ts_ms"] < 0:
            return "ts_ms must be a non-negative integer"
        if "actor" in r and r["actor"] is not None:
            a = r["actor"]
            if not isinstance(a, dict) or not isinstance(a.get("agent"), str) or not isinstance(a.get("user"), str):
                return "malformed actor"
        if "prev_hash" in r and r["prev_hash"] is not None and not isinstance(r["prev_hash"], str):
            return "prev_hash must be a string"
        pk = r.get("public_key")
        sig = r.get("signature")
        if not isinstance(pk, str) or not HEX64.match(pk):
            return "public_key must be 32 bytes of lowercase hex"
        if not isinstance(sig, str) or not HEX128.match(sig):
            return "signature must be 64 bytes of lowercase hex"
        msg = canonical_bytes(r)
        Ed25519PublicKey.from_public_bytes(bytes.fromhex(pk)).verify(bytes.fromhex(sig), msg)
        return None
    except InvalidSignature:
        return "signature does not match"
    except (ValueError, KeyError, TypeError) as e:
        return f"malformed receipt: {e}"


def chain_break(raw_lines):
    """1-based index of the first line breaking the chain, or None. The digest is
    over the exact transmitted octets of the previous line — never re-serialized."""
    prev = None
    for i, line in enumerate(raw_lines):
        try:
            parsed = json.loads(line)
            declared = parsed.get("prev_hash")
            if not isinstance(declared, str):
                declared = None
        except json.JSONDecodeError:
            return i + 1
        if declared != prev:
            return i + 1
        prev = hashlib.sha256(line.encode("utf-8")).hexdigest()
    return None


def verify_log(path):
    raw = [l for l in Path(path).read_text(encoding="utf-8").split("\n") if l.strip()]
    sig_failures = []
    for i, line in enumerate(raw):
        try:
            reason = verify_receipt(json.loads(line))
        except json.JSONDecodeError as e:
            reason = f"JSON parse error: {e}"
        if reason is not None:
            sig_failures.append((i + 1, reason))
    return sig_failures, chain_break(raw), len(raw)


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == "--manifest":
        root = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).parent
        manifest = json.loads((root / "manifest.json").read_text())
        disagreements = 0
        for v in manifest["vectors"]:
            fails, cb, _ = verify_log(root / "vectors" / v["file"])
            got = {"sig_failures": [n for n, _ in fails], "chain_break": cb}
            want = v["expect"]
            ok = got == want
            disagreements += 0 if ok else 1
            print(f"{'AGREE ' if ok else 'DISAGREE'} {v['file']}: {json.dumps(got)}"
                  + ("" if ok else f" expected {json.dumps(want)}"))
        print(f"\n{len(manifest['vectors'])} vectors, {disagreements} disagreement(s)")
        sys.exit(1 if disagreements else 0)

    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(2)
    fails, cb, n = verify_log(sys.argv[1])
    for line_no, reason in fails:
        print(f"line {line_no}: SIGNATURE FAIL — {reason}")
    print(f"{n} lines; signatures: {n - len(fails)} ok, {len(fails)} failed; "
          + (f"chain BREAK at line {cb}" if cb else "chain intact"))
    sys.exit(1 if (fails or cb) else 0)


if __name__ == "__main__":
    main()
